### ISSUE TITLE
this is title for creating comment ,this is title for creating comment s title for creating comment 

### ISSUE THREAD

**Issue by mvamshikrishna** [krishnsvamshi/localities#49]
1.this is title for creating comment ,this is title for creating comment s title for creating com
2.this is title for creating comment ,this is title for creating comment s title for creating com
this is title for creating comment ,this is title for creating comment s title for creating com sdkfjhsdfsdfjklsd
sdfkjhsdfkjhmsdkjh sdkjhkdsfksdf sdkfjhskdjfsdkjhf 
![yellow_and_black_balls-wallpaper-1920x1080](https://cloud.githubusercontent.com/assets/18001108/14109948/295668c6-f5e2-11e5-80f4-ce17fe3b136f.jpg)

**Comment by krishnsvamshi** [comment]
,this si comment for closing issue,this si comment for closing issue,this si comment for closing issue,this si comment for closing issue
this si comment for closing issue
![blur-background08](https://cloud.githubusercontent.com/assets/17740598/14134181/be2e299e-f672-11e5-96b3-b021b2ca4330.jpg)
